// Typed entry point: wraps the raw `wasm-bindgen` bindings (`../pkg/`, generated by `wasm-pack
// build --target web`, `any`-typed) with the hand-written types in `./types.ts` so consumers get
// a fully-typed API, and handles instantiating the wasm module for both a browser and Node.

import wasmInit, {
  listCombatants as rawListCombatants,
  parseLine as rawParseLine,
  version as rawVersion,
} from "../pkg/fellowship_combat_log.js";

import type { Combatant, Event } from "./types.js";

export type {
  Cast,
  CastPhase,
  Combatant,
  CombatantInfo,
  DamageAbsorbed,
  DamageHeal,
  DamageHealKind,
  Death,
  DeathKind,
  Dispel,
  DungeonEnd,
  DungeonStart,
  Effect,
  EffectPhase,
  Encounter,
  EncounterPhase,
  Event,
  EventBody,
  GearPiece,
  Guid,
  Interrupt,
  LogInstant,
  LoggingStarted,
  MapChange,
  Marker,
  NeckTraitChoice,
  Polarity,
  ResourceChange,
  ResultTier,
  Resurrect,
  School,
  WorldMarker,
  ZoneChange,
} from "./types.js";

function isNode(): boolean {
  return (
    typeof process !== "undefined" &&
    process.versions != null &&
    process.versions.node != null
  );
}

let readyPromise: Promise<void> | undefined;

/**
 * Instantiate the wasm module. `parseLine`, `listCombatants`, and `version` all call this
 * themselves and share its result, so most callers never need to call it directly — it is
 * exposed for a caller that wants to control *when* the one-time instantiation cost (reading the
 * `.wasm` file in Node; fetching it in a browser) is paid, e.g. to warm it up during an
 * application's own startup sequence rather than on the first decode call.
 *
 * Safe to call more than once, including concurrently: every call after the first awaits the
 * same in-flight (or already completed) initialization.
 */
export function init(): Promise<void> {
  if (!readyPromise) {
    readyPromise = doInit();
  }
  return readyPromise;
}

async function doInit(): Promise<void> {
  if (isNode()) {
    // The generated glue's zero-argument path resolves the `.wasm` file to a `file:` URL and
    // `fetch`es it — Node's `fetch` does not support `file:` URLs, so in Node we read the bytes
    // ourselves with `node:fs` and hand them to `wasmInit` directly, bypassing `fetch` entirely.
    // The dynamic imports below only ever execute in this Node branch; see the README for the
    // bundler caveat this implies for browser builds.
    const { readFile } = await import("node:fs/promises");
    const wasmUrl = new URL("../pkg/fellowship_combat_log_bg.wasm", import.meta.url);
    const bytes = await readFile(wasmUrl);
    // Wrapped in the `{ module_or_path }` object form (rather than passing `bytes` directly) so
    // the generated glue takes its non-deprecated argument-shape branch.
    await wasmInit({ module_or_path: bytes });
  } else {
    await wasmInit();
  }
}

/**
 * Decode one v8 combat-log line. `seq` is the file line number (1-based) — the ordering
 * tiebreaker for sub-millisecond ties, and the number an error message reports on failure.
 *
 * Rejects with an `Error` on a malformed line, rather than returning some ok/error union, so a
 * caller can `try`/`catch` (or `.catch`) it the same way any other JS decoding failure works.
 */
export async function parseLine(seq: number, line: string): Promise<Event> {
  await init();
  return rawParseLine(seq, line) as Event;
}

/**
 * List every combatant a log mentions, in first-seen order, each carrying its latest
 * `COMBATANT_INFO` gear snapshot.
 *
 * Malformed or unparseable lines are skipped rather than failing the scan, so this never rejects.
 */
export async function listCombatants(log: string): Promise<Combatant[]> {
  await init();
  return rawListCombatants(log) as Combatant[];
}

/**
 * This decoder's version, for a consumer that records which decoder produced a result and wants
 * to detect staleness after an upgrade.
 */
export async function version(): Promise<string> {
  await init();
  return rawVersion();
}
